<?php

namespace App\Tests\Infrastructure\Search\DeNormalizer;

use App\Infrastructure\Search\DeNormalizer\SearchableDeNormalizer;
use App\Tests\TestCase;


class SearchableDeNormalizerTest extends TestCase
{
    private SearchableDeNormalizer $searchableDeNormalizer;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->searchableDeNormalizer = new SearchableDeNormalizer();
    }

    public function testSearchableFormatterTest(): void
    {
        $this->assertEquals($this->dataResult(), $this->normalize($this->searchableDeNormalizer->format($this->dataProvider())));
    }

    public function dataResult(): array
    {
        return
            [
                [
                    'id' => 27,
                    'name' => 'city',
                    'searchableItems' =>
                        [
                            [
                                'id' => 27,
                                'label' => 'lyon',
                                'name' => 'lyon',
                            ],
                        ],
                ],
                [
                    'id' => 32,
                    'name' => 'product_cat',
                    'searchableItems' =>
                        [
                            [
                                'id' => 32,
                                'label' => 'Pierre',
                                'name' => 'pierre',
                            ],
                        ],
                ],
                [
                    'id' => 2,
                    'name' => 'product_type',
                    'searchableItems' =>
                        [
                            [
                                'id' => 2,
                                'label' => 'simple',
                                'name' => 'simple',
                            ],
                        ],
                ],
            ];
    }

    public function dataProvider(): array
    {
        return [
            [
                'searchableItemId' => '27',
                'searchableItemLabel' => 'lyon',
                'searchableItemName' => 'lyon',
                'searchableName' => 'city',
                'searchableId' => '27',
            ],
            [
                'searchableItemId' => '32',
                'searchableItemLabel' => 'Pierre',
                'searchableItemName' => 'pierre',
                'searchableName' => 'product_cat',
                'searchableId' => '32',
            ],
            [
                'searchableItemId' => '2',
                'searchableItemLabel' => 'simple',
                'searchableItemName' => 'simple',
                'searchableName' => 'product_type',
                'searchableId' => '2',
            ],
        ];
    }
}
